package puxped.bundleditems;

import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.minecraft.item.Item;
import net.minecraft.item.Items;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;
import puxped.bundleditems.items.BundledItem;
import puxped.bundleditems.items.BundledItemWithGlint;
import puxped.bundleditems.items.BundledWaterBottle;

public class BIItems {

    public static final Item SECRET_ITEM = new Item(new FabricItemSettings().maxCount(1));

    public static final Item BUNDLED_OAK_SAPLINGS = new BundledItem(new FabricItemSettings().maxCount(32), Items.OAK_SAPLING, null);
    public static final Item BUNDLED_SPRUCE_SAPLINGS = new BundledItem(new FabricItemSettings().maxCount(32), Items.SPRUCE_SAPLING, null);
    public static final Item BUNDLED_BIRCH_SAPLINGS = new BundledItem(new FabricItemSettings().maxCount(32), Items.BIRCH_SAPLING, null);
    public static final Item BUNDLED_JUNGLE_SAPLINGS = new BundledItem(new FabricItemSettings().maxCount(32), Items.JUNGLE_SAPLING, null);
    public static final Item BUNDLED_ACACIA_SAPLINGS = new BundledItem(new FabricItemSettings().maxCount(32), Items.ACACIA_SAPLING, null);
    public static final Item BUNDLED_DARK_OAK_SAPLINGS = new BundledItem(new FabricItemSettings().maxCount(32), Items.DARK_OAK_SAPLING, null);
    public static final Item BUNDLED_DANDELIONS = new BundledItem(new FabricItemSettings().maxCount(32), Items.DANDELION, Items.PAPER);
    public static final Item BUNDLED_POPPIES = new BundledItem(new FabricItemSettings().maxCount(32), Items.POPPY, Items.PAPER);
    public static final Item BUNDLED_BLUE_ORCHIDS = new BundledItem(new FabricItemSettings().maxCount(32), Items.BLUE_ORCHID, Items.PAPER);
    public static final Item BUNDLED_ALLIUMS = new BundledItem(new FabricItemSettings().maxCount(32), Items.ALLIUM, Items.PAPER);
    public static final Item BUNDLED_AZURE_BLUETS = new BundledItem(new FabricItemSettings().maxCount(32), Items.AZURE_BLUET, Items.PAPER);
    public static final Item BUNDLED_RED_TULIPS = new BundledItem(new FabricItemSettings().maxCount(32), Items.RED_TULIP, Items.PAPER);
    public static final Item BUNDLED_ORANGE_TULIPS = new BundledItem(new FabricItemSettings().maxCount(32), Items.ORANGE_TULIP, Items.PAPER);
    public static final Item BUNDLED_WHITE_TULIPS = new BundledItem(new FabricItemSettings().maxCount(32), Items.WHITE_TULIP, Items.PAPER);
    public static final Item BUNDLED_PINK_TULIPS = new BundledItem(new FabricItemSettings().maxCount(32), Items.PINK_TULIP, Items.PAPER);
    public static final Item BUNDLED_OXEYE_DAISIES = new BundledItem(new FabricItemSettings().maxCount(32), Items.OXEYE_DAISY, Items.PAPER);
    public static final Item BUNDLED_CORNFLOWERS = new BundledItem(new FabricItemSettings().maxCount(32), Items.CORNFLOWER, Items.PAPER);
    public static final Item BUNDLED_LILIES_OF_THE_VALLEY = new BundledItem(new FabricItemSettings().maxCount(32), Items.LILY_OF_THE_VALLEY, Items.PAPER);
    public static final Item BUNDLED_WITHER_ROSES = new BundledItem(new FabricItemSettings().maxCount(32), Items.WITHER_ROSE, Items.PAPER);
    public static final Item BUNDLED_VINES = new BundledItem(new FabricItemSettings().maxCount(32), Items.VINE, null);
    public static final Item BUNDLED_APPLES = new BundledItem(new FabricItemSettings().maxCount(32), Items.APPLE, Items.BOWL);
    public static final Item BUNDLED_GOLDEN_APPLES = new BundledItem(new FabricItemSettings().maxCount(32), Items.GOLDEN_APPLE, Items.BOWL);
    public static final Item BUNDLED_ENCHANTED_GOLDEN_APPLES = new BundledItemWithGlint(new FabricItemSettings().maxCount(32), Items.ENCHANTED_GOLDEN_APPLE, Items.BOWL);
    public static final Item QUIVER = new Item(new FabricItemSettings().maxCount(64));
    public static final Item BUNDLED_ARROWS = new BundledItem(new FabricItemSettings().maxCount(32), Items.ARROW, QUIVER);
    public static final Item BUNDLED_BONES = new BundledItem(new FabricItemSettings().maxCount(32), Items.BONE, null);
    public static final Item BUNDLED_STICKS = new BundledItem(new FabricItemSettings().maxCount(32), Items.STICK, null);
    public static final Item BUNDLED_BLAZE_RODS = new BundledItem(new FabricItemSettings().maxCount(32), Items.BLAZE_ROD, null);
    public static final Item BUNDLED_BOWLS = new BundledItem(new FabricItemSettings().maxCount(32), Items.BOWL, null);
    public static final Item BUNDLED_SNOWBALLS = new BundledItem(new FabricItemSettings().maxCount(32), Items.SNOWBALL, Items.BOWL);
    public static final Item BUNDLED_SLIME_BALLS = new BundledItem(new FabricItemSettings().maxCount(32), Items.SLIME_BALL, Items.BOWL);
    public static final Item BUNDLED_BLAZE_POWDER = new BundledItem(new FabricItemSettings().maxCount(32), Items.BLAZE_POWDER, Items.BOWL);
    public static final Item BUNDLED_CLAY_BALLS = new BundledItem(new FabricItemSettings().maxCount(32), Items.CLAY_BALL, Items.BOWL);
    public static final Item BUNDLED_NETHER_WARTS = new BundledItem(new FabricItemSettings().maxCount(32), Items.NETHER_WART, Items.BOWL);
    public static final Item BUNDLED_STRING = new BundledItem(new FabricItemSettings().maxCount(32), Items.STRING, null);
    public static final Item BUNDLED_FEATHERS = new BundledItem(new FabricItemSettings().maxCount(32), Items.FEATHER, null);
    public static final Item BUNDLED_GLASS_BOTTLES = new BundledItem(new FabricItemSettings().maxCount(32), Items.GLASS_BOTTLE, null);
    public static final Item BUNDLED_WATER_BOTTLES = new BundledWaterBottle(new FabricItemSettings().maxCount(32));
    public static final Item GLASS_VIAL = new Item(new FabricItemSettings().maxCount(64));
    public static final Item BUNDLED_GLOWSTONE_DUST = new BundledItem(new FabricItemSettings().maxCount(32), Items.GLOWSTONE, GLASS_VIAL);
    public static final Item BUNDLED_GUNPOWDER = new BundledItem(new FabricItemSettings().maxCount(32), Items.GUNPOWDER, GLASS_VIAL);
    public static final Item BUNDLED_REDSTONE = new BundledItem(new FabricItemSettings().maxCount(32), Items.REDSTONE, GLASS_VIAL);
    public static final Item BUNDLED_SUGAR = new BundledItem(new FabricItemSettings().maxCount(32), Items.SUGAR, GLASS_VIAL);
    public static final Item BUNDLED_SEEDS = new BundledItem(new FabricItemSettings().maxCount(32), Items.WHEAT_SEEDS, null);
    public static final Item BUNDLED_BREAD = new BundledItem(new FabricItemSettings().maxCount(32), Items.BREAD, null);
    public static final Item BUNDLED_FLINTS = new BundledItem(new FabricItemSettings().maxCount(32), Items.FLINT, null);
    public static final Item BUNDLED_BUCKETS = new BundledItem(new FabricItemSettings().maxCount(32), Items.BUCKET, null);
    public static final Item BUNDLED_NAME_TAGS = new BundledItem(new FabricItemSettings().maxCount(32), Items.NAME_TAG, null);
    public static final Item BUNDLED_PORKCHOP = new BundledItem(new FabricItemSettings().maxCount(32), Items.PORKCHOP, null);
    public static final Item BUNDLED_COOKED_PORKCHOP = new BundledItem(new FabricItemSettings().maxCount(32), Items.COOKED_PORKCHOP, null);
    public static final Item BUNDLED_RAW_BEEF = new BundledItem(new FabricItemSettings().maxCount(32), Items.BEEF, null);
    public static final Item BUNDLED_COOKED_BEEF = new BundledItem(new FabricItemSettings().maxCount(32), Items.COOKED_BEEF, null);
    public static final Item BUNDLED_RAW_CHICKEN = new BundledItem(new FabricItemSettings().maxCount(32), Items.CHICKEN, null);
    public static final Item BUNDLED_COOKED_CHICKEN = new BundledItem(new FabricItemSettings().maxCount(32), Items.COOKED_CHICKEN, null);
    public static final Item BUNDLED_RAW_MUTTON = new BundledItem(new FabricItemSettings().maxCount(32), Items.MUTTON, null);
    public static final Item BUNDLED_COOKED_MUTTON = new BundledItem(new FabricItemSettings().maxCount(32), Items.COOKED_MUTTON, null);
    public static final Item BUNDLED_RAW_RABBIT = new BundledItem(new FabricItemSettings().maxCount(32), Items.RABBIT, null);
    public static final Item BUNDLED_COOKED_RABBIT = new BundledItem(new FabricItemSettings().maxCount(32), Items.COOKED_RABBIT, null);
    public static final Item BUNDLED_ROTTEN_FLESH = new BundledItem(new FabricItemSettings().maxCount(32), Items.ROTTEN_FLESH, null);
    public static final Item BUNDLED_LEATHER = new BundledItem(new FabricItemSettings().maxCount(32), Items.LEATHER, null);
    public static final Item BUNDLED_BRICKS = new BundledItem(new FabricItemSettings().maxCount(32), Items.BRICKS, null);
    public static final Item BUNDLED_NETHER_BRICKS = new BundledItem(new FabricItemSettings().maxCount(32), Items.NETHER_BRICK, null);
    public static final Item BUNDLED_SUGAR_CANE = new BundledItem(new FabricItemSettings().maxCount(32), Items.SUGAR_CANE, null);
    public static final Item BUNDLED_PAPER = new BundledItem(new FabricItemSettings().maxCount(32), Items.PAPER, null);
    public static final Item BUNDLED_BOOKS = new BundledItem(new FabricItemSettings().maxCount(32), Items.BOOK, null);
    public static final Item BUNDLED_COD = new BundledItem(new FabricItemSettings().maxCount(32), Items.COD, null);
    public static final Item BUNDLED_COOKED_COD = new BundledItem(new FabricItemSettings().maxCount(32), Items.COOKED_COD, null);
    public static final Item BUNDLED_SALMON = new BundledItem(new FabricItemSettings().maxCount(32), Items.SALMON, null);
    public static final Item BUNDLED_COOKED_SALMON = new BundledItem(new FabricItemSettings().maxCount(32), Items.SALMON, null);
    public static final Item BUNDLED_CARROTS = new BundledItem(new FabricItemSettings().maxCount(32), Items.CARROT, null);
    public static final Item BUNDLED_GOLDEN_CARROTS = new BundledItem(new FabricItemSettings().maxCount(32), Items.GOLDEN_CARROT, null);
    public static final Item BUNDLED_POTATOES = new BundledItem(new FabricItemSettings().maxCount(32), Items.POTATO, Items.BOWL);
    public static final Item BUNDLED_BAKED_POTATOES = new BundledItem(new FabricItemSettings().maxCount(32), Items.BAKED_POTATO, null);
    public static final Item BUNDLED_NETHER_STARS = new BundledItemWithGlint(new FabricItemSettings().maxCount(32), Items.NETHER_STAR, null);
    public static final Item BUNDLED_FIREWORKS = new BundledItem(new FabricItemSettings().maxCount(32), Items.FIREWORK_ROCKET, null);
    public static final Item BUNDLED_CHORUS_FRUIT = new BundledItem(new FabricItemSettings().maxCount(32), Items.CHORUS_FRUIT, null);
    public static final Item BUNDLED_POPPED_CHORUS_FRUIT = new BundledItem(new FabricItemSettings().maxCount(32), Items.POPPED_CHORUS_FRUIT, null);
    // 1.5.0
    public static final Item JAR = new Item(new FabricItemSettings().maxCount(64));
    public static final Item BUNDLED_CHARCOAL = new BundledItem(new FabricItemSettings().maxCount(32), Items.CHARCOAL, Items.BOWL);
    public static final Item BUNDLED_GHAST_TEARS = new BundledItem(new FabricItemSettings().maxCount(32), Items.GHAST_TEAR, GLASS_VIAL);
    public static final Item BUNDLED_GLOW_BERRIES = new BundledItem(new FabricItemSettings().maxCount(32), Items.GLOW_BERRIES, Items.BOWL);
    public static final Item BUNDLED_HONEY = new BundledItem(new FabricItemSettings().maxCount(32), Items.HONEY_BOTTLE, JAR);
    public static final Item BUNDLED_COOKIES = new BundledItem(new FabricItemSettings().maxCount(32), Items.COOKIE, JAR);
    public static final Item BUNDLED_HONEYCOMB = new BundledItem(new FabricItemSettings().maxCount(32), Items.HONEYCOMB, JAR);
    public static final Item BUNDLED_EGGS = new BundledItem(new FabricItemSettings().maxCount(32), Items.HONEYCOMB, JAR);
    
    public static void regItems() {
        registerItem("secret_item", SECRET_ITEM);
        registerItem("bundled_oak_saplings", BUNDLED_OAK_SAPLINGS);
        registerItem("bundled_spruce_saplings", BUNDLED_SPRUCE_SAPLINGS);
        registerItem("bundled_birch_saplings", BUNDLED_BIRCH_SAPLINGS);
        registerItem("bundled_jungle_saplings", BUNDLED_JUNGLE_SAPLINGS);
        registerItem("bundled_acacia_saplings", BUNDLED_ACACIA_SAPLINGS);
        registerItem("bundled_dark_oak_saplings", BUNDLED_DARK_OAK_SAPLINGS);
        registerItem("bundled_dandelions", BUNDLED_DANDELIONS);
        registerItem("bundled_poppies", BUNDLED_POPPIES);
        registerItem("bundled_blue_orchids", BUNDLED_BLUE_ORCHIDS);
        registerItem("bundled_alliums", BUNDLED_ALLIUMS);
        registerItem("bundled_azure_bluets", BUNDLED_AZURE_BLUETS);
        registerItem("bundled_red_tulips", BUNDLED_RED_TULIPS);
        registerItem("bundled_orange_tulips", BUNDLED_ORANGE_TULIPS);
        registerItem("bundled_white_tulips", BUNDLED_WHITE_TULIPS);
        registerItem("bundled_pink_tulips", BUNDLED_PINK_TULIPS);
        registerItem("bundled_oxeye_daisies", BUNDLED_OXEYE_DAISIES);
        registerItem("bundled_cornflowers", BUNDLED_CORNFLOWERS);
        registerItem("bundled_lilies_of_the_valley", BUNDLED_LILIES_OF_THE_VALLEY);
        registerItem("bundled_wither_roses", BUNDLED_WITHER_ROSES);
        registerItem("bundled_vines", BUNDLED_VINES);
        registerItem("bundled_apples", BUNDLED_APPLES);
        registerItem("bundled_golden_apples", BUNDLED_GOLDEN_APPLES);
        registerItem("bundled_enchanted_golden_apples", BUNDLED_ENCHANTED_GOLDEN_APPLES);
        registerItem("quiver", QUIVER);
        registerItem("bundled_arrows", BUNDLED_ARROWS);
        registerItem("bundled_bones", BUNDLED_BONES);
        registerItem("bundled_sticks", BUNDLED_STICKS);
        registerItem("bundled_blaze_rods", BUNDLED_BLAZE_RODS);
        registerItem("bundled_bowls", BUNDLED_BOWLS);
        registerItem("bundled_snowballs", BUNDLED_SNOWBALLS);
        registerItem("bundled_slimeballs", BUNDLED_SLIME_BALLS);
        registerItem("bundled_blaze_powder", BUNDLED_BLAZE_POWDER);
        registerItem("bundled_clay_balls", BUNDLED_CLAY_BALLS);
        registerItem("bundled_nether_warts", BUNDLED_NETHER_WARTS);
        registerItem("bundled_string", BUNDLED_STRING);
        registerItem("bundled_feathers", BUNDLED_FEATHERS);
        registerItem("bundled_empty_bottles", BUNDLED_GLASS_BOTTLES);
        registerItem("bundled_water_bottles", BUNDLED_WATER_BOTTLES);
        registerItem("small_bottle", GLASS_VIAL);
        registerItem("bundled_glowstone_dust", BUNDLED_GLOWSTONE_DUST);
        registerItem("bundled_gunpowder", BUNDLED_GUNPOWDER);
        registerItem("bundled_redstone", BUNDLED_REDSTONE);
        registerItem("bundled_sugar", BUNDLED_SUGAR);
        registerItem("bundled_seeds", BUNDLED_SEEDS);
        registerItem("bundled_bread", BUNDLED_BREAD);
        registerItem("bundled_flints", BUNDLED_FLINTS);
        registerItem("bundled_buckets", BUNDLED_BUCKETS);
        registerItem("bundled_name_tags", BUNDLED_NAME_TAGS);
        registerItem("bundled_porkchop", BUNDLED_PORKCHOP);
        registerItem("bundled_cooked_porkchop", BUNDLED_COOKED_PORKCHOP);
        registerItem("bundled_raw_beef", BUNDLED_RAW_BEEF);
        registerItem("bundled_cooked_beef", BUNDLED_COOKED_BEEF);
        registerItem("bundled_raw_chicken", BUNDLED_RAW_CHICKEN);
        registerItem("bundled_cooked_chicken", BUNDLED_COOKED_CHICKEN);
        registerItem("bundled_raw_mutton", BUNDLED_RAW_MUTTON);
        registerItem("bundled_cooked_mutton", BUNDLED_COOKED_MUTTON);
        registerItem("bundled_raw_rabbit", BUNDLED_RAW_RABBIT);
        registerItem("bundled_cooked_rabbit", BUNDLED_COOKED_RABBIT);
        registerItem("bundled_rotten_flesh", BUNDLED_ROTTEN_FLESH);
        registerItem("bundled_leather", BUNDLED_LEATHER);
        registerItem("bundled_bricks", BUNDLED_BRICKS);
        registerItem("bundled_netherbricks", BUNDLED_NETHER_BRICKS);
        registerItem("bundled_sugar_cane", BUNDLED_SUGAR_CANE);
        registerItem("bundled_paper", BUNDLED_PAPER);
        registerItem("bundled_books", BUNDLED_BOOKS);
        registerItem("bundled_cod", BUNDLED_COD);
        registerItem("bundled_salmon", BUNDLED_SALMON);
        registerItem("bundled_cooked_cod", BUNDLED_COOKED_COD);
        registerItem("bundled_cooked_salmon", BUNDLED_COOKED_SALMON);
        registerItem("bundled_carrots", BUNDLED_CARROTS);
        registerItem("bundled_golden_carrots", BUNDLED_GOLDEN_CARROTS);
        registerItem("bundled_potatoes", BUNDLED_POTATOES);
        registerItem("bundled_baked_potatoes", BUNDLED_BAKED_POTATOES);
        registerItem("bundled_nether_stars", BUNDLED_NETHER_STARS);
        registerItem("bundled_fireworks", BUNDLED_FIREWORKS);
        registerItem("bundled_chorus_fruits", BUNDLED_CHORUS_FRUIT);
        registerItem("bundled_popped_chorus_fruits", BUNDLED_POPPED_CHORUS_FRUIT);
        // 1.5.0
        registerItem("bundled_charcoal", BUNDLED_CHARCOAL);
        registerItem("bundled_ghast_tears", BUNDLED_GHAST_TEARS);
        registerItem("bundled_glow_berries", BUNDLED_GLOW_BERRIES);
        registerItem("jar", JAR);
        registerItem("bundled_cookies", BUNDLED_COOKIES);
        registerItem("bundled_honey", BUNDLED_HONEY);
        registerItem("bundled_eggs", BUNDLED_EGGS);
    }

    public static void registerItem(String itemName, Item item) {
        Registry.register(Registries.ITEM, new Identifier("bundleditems", itemName), item);
    }
}
